/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.Categoria;
/**
 *
 * @author alumnogreibd
 */
public class VCategorias extends javax.swing.JDialog {
    private aplicacion.FachadaAplicacion fa;
    private java.util.List<Categoria> categorias;
   /**
     * Creates new form VCategorias
     * @param parent
     * @param modal
     * @param fa
     */
    public VCategorias(java.awt.Frame parent, boolean modal,aplicacion.FachadaAplicacion fa  ) {
        super(parent, modal);
        initComponents();
        this.fa=fa;
        this.categorias = new java.util.ArrayList<Categoria>();
        this.cargarCategorias();
        if(categorias.size()>0){
            this.textoNombre.setText(categorias.get(0).getNombre());
            this.textoDescripcion.setText(categorias.get(0).getDescripcion());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaCategorias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCategorias = new javax.swing.JList();
        etiquetaNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        etiquetaDescripcion = new javax.swing.JLabel();
        botonAnadir = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorías");
        setResizable(false);

        etiquetaCategorias.setText("CATEGORíAS");

        listaCategorias.setModel(new ModeloListaStrings());
        listaCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCategorias);

        etiquetaNombre.setText("Nombre:");

        etiquetaDescripcion.setText("Descripción:");

        botonAnadir.setText("Añadir");
        botonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirActionPerformed(evt);
            }
        });

        BotonBorrar.setText("Borrar");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textoDescripcion.setColumns(20);
        textoDescripcion.setLineWrap(true);
        textoDescripcion.setRows(5);
        textoDescripcion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textoDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaDescripcion)
                        .addGap(201, 201, 201))
                    .addComponent(jScrollPane2))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(etiquetaCategorias)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaNombre)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(etiquetaDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonBorrar)
                            .addComponent(botonAnadir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
        if(!textoNombre.getText().equals("")){
            fa.anhadirCategoria(textoNombre.getText(),textoDescripcion.getText());
            this.cargarCategorias();
            this.textoNombre.setText("");
            this.textoDescripcion.setText("");
        }
    }//GEN-LAST:event_botonAnadirActionPerformed

    private void listaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCategoriasMouseClicked
        //ModeloListaStrings mListaRC=new ModeloListaStrings();
        //listaCategorias.setModel(mListaRC);
        if (categorias.size()>listaCategorias.getSelectedIndex()) {
            Categoria ca =this.categorias.get(listaCategorias.getSelectedIndex());
            this.textoNombre.setText(ca.getNombre());
            this.textoDescripcion.setText(ca.getDescripcion());
        }
        
    }//GEN-LAST:event_listaCategoriasMouseClicked

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        fa.borrarCategoria(this.categorias.get(listaCategorias.getSelectedIndex()).getNombre());
        this.cargarCategorias();
        if(categorias.size()>0){
            this.textoNombre.setText(categorias.get(0).getNombre());
            this.textoDescripcion.setText(categorias.get(0).getDescripcion());
        }
        /*
        this.textoNombre.setText("");
        this.textoDescripcion.setText("");
                */
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void cargarCategorias(){
        this.categorias=fa.obtenerCategorias();
        ModeloListaStrings mListaRC=new ModeloListaStrings();
        listaCategorias.setModel(mListaRC);
        java.util.List<String> categoriasNombre = new java.util.ArrayList<String>();
        for(Categoria c:categorias){
            categoriasNombre.add(c.getNombre());
        }
        mListaRC.setElementos(categoriasNombre);
        if (mListaRC.getSize()>0) {
            listaCategorias.setSelectedIndex(0);    
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton botonAnadir;
    private javax.swing.JLabel etiquetaCategorias;
    private javax.swing.JLabel etiquetaDescripcion;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaCategorias;
    private javax.swing.JTextArea textoDescripcion;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
