/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import aplicacion.TipoUsuario;
import aplicacion.Usuario;

/**
 *
 * @author alumnogreibd
 */
public class VUsuarios extends javax.swing.JDialog {
    private aplicacion.FachadaAplicacion fa;

    /**
     * Creates new form MenuUsuarios
     */
    public VUsuarios(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        initComponents();
        this.fa=fa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarID = new javax.swing.JTextField();
        etiquetaID = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        buscarNombre = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        etiquetaIdNuevo = new javax.swing.JLabel();
        textoIdNuevo = new javax.swing.JTextField();
        etiquetaClave = new javax.swing.JLabel();
        textoClave = new javax.swing.JTextField();
        etiquetaTipo = new javax.swing.JLabel();
        etiquetaNombreNuevo = new javax.swing.JLabel();
        textoNombreNuevo = new javax.swing.JTextField();
        etiquetaEmail = new javax.swing.JLabel();
        textoEmail = new javax.swing.JTextField();
        etiquetaDireccion = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestación de Usuarios");
        setResizable(false);

        etiquetaID.setText("Id:");

        etiquetaNombre.setText("Nombre:");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        tablaUsuarios.setModel(new ModeloTablaUsuarios());
        tablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);
        tablaUsuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        etiquetaIdNuevo.setText("Id:");

        etiquetaClave.setText("Clave:");

        textoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClaveActionPerformed(evt);
            }
        });

        etiquetaTipo.setText("Tipo:");

        etiquetaNombreNuevo.setText("Nombre:");

        etiquetaEmail.setText("Email:");

        etiquetaDireccion.setText("Dirección:");

        textoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDireccionActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Administrador" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaID)
                        .addGap(4, 4, 4)
                        .addComponent(buscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(etiquetaNombre)
                        .addGap(6, 6, 6)
                        .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(botonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaNombreNuevo)
                                        .addGap(4, 4, 4)
                                        .addComponent(textoNombreNuevo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaIdNuevo)
                                        .addGap(4, 4, 4)
                                        .addComponent(textoIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaClave)
                                    .addComponent(etiquetaEmail))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoClave)
                                    .addComponent(textoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaTipo)
                                .addGap(3, 3, 3)
                                .addComponent(comboTipo, 0, 124, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaDireccion)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoDireccion))))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaID)
                    .addComponent(etiquetaNombre)
                    .addComponent(buscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaIdNuevo)
                    .addComponent(textoIdNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaClave)
                    .addComponent(textoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTipo)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombreNuevo)
                    .addComponent(textoNombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaEmail)
                    .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaDireccion)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonBorrar)
                    .addComponent(botonSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        buscarUsuarios();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void textoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClaveActionPerformed

    private void textoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDireccionActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(tablaUsuarios.getSelectionModel().isSelectionEmpty()){
            if(textoIdNuevo.getText().equals("")||textoClave.getText().equals("")) return;
            fa.nuevoUsuario(textoIdNuevo.getText(),textoClave.getText()
                            ,textoNombreNuevo.getText(),textoDireccion.getText()
                            ,textoEmail.getText(), (String)comboTipo.getSelectedItem());
        }else{
            if(textoClave.getText().equals("")) return;
            boolean ultimoAdmin=true;
            Usuario usr =((ModeloTablaUsuarios)tablaUsuarios.getModel()).getUsuario(tablaUsuarios.getSelectedRow());
            if(((String)comboTipo.getSelectedItem()).equals("Normal")){
                for(Usuario u:((ModeloTablaUsuarios)tablaUsuarios.getModel()).getFilas()){
                    if(!u.equals(usr) && u.getTipoUsuario().equals(TipoUsuario.Administrador)){
                        ultimoAdmin=false;
                        break;
                    }
                }
                if(!ultimoAdmin){
                    fa.actualizarUsuario(textoIdNuevo.getText(),textoClave.getText()
                            ,textoNombreNuevo.getText(),textoDireccion.getText()
                            ,textoEmail.getText(), (String)comboTipo.getSelectedItem());
                }else{
                    fa.muestraExcepcion("Operacion no valida: Siempre debe haber un administrador");
                }
            }else{    
            fa.actualizarUsuario(textoIdNuevo.getText(),textoClave.getText()
                            ,textoNombreNuevo.getText(),textoDireccion.getText()
                            ,textoEmail.getText(), (String)comboTipo.getSelectedItem());
            }
        }
        buscarUsuarios();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if(!tablaUsuarios.getSelectionModel().isSelectionEmpty()){         
            boolean ultimoAdmin=true;
            Usuario usr =((ModeloTablaUsuarios)tablaUsuarios.getModel()).getUsuario(tablaUsuarios.getSelectedRow());
            if(usr.getTipoUsuario().equals(TipoUsuario.Administrador)){
                for(Usuario u:((ModeloTablaUsuarios)tablaUsuarios.getModel()).getFilas()){
                    if(!u.equals(usr) && u.getTipoUsuario().equals(TipoUsuario.Administrador)){
                        ultimoAdmin=false;
                        break;
                    }
                }
                if(!ultimoAdmin) fa.borrarUsuario(usr);
                else{
                    fa.muestraExcepcion("Operacion no valida: Siempre debe haber un administrador");
                }
            }else fa.borrarUsuario(usr);
        }
        buscarUsuarios();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        //textoIdNuevo.setText(tablaUsuarios.getSelected(()));
        this.cargarSeleccion();
       
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        textoIdNuevo.setEditable(true);
        tablaUsuarios.clearSelection();
        textoIdNuevo.setText("");
        textoNombreNuevo.setText("");
        textoClave.setText("");
        textoEmail.setText("");
        textoDireccion.setText("");
        comboTipo.setSelectedIndex(0);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField buscarID;
    private javax.swing.JTextField buscarNombre;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JLabel etiquetaID;
    private javax.swing.JLabel etiquetaIdNuevo;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaNombreNuevo;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField textoClave;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoIdNuevo;
    private javax.swing.JTextField textoNombreNuevo;
    // End of variables declaration//GEN-END:variables

    public void buscarUsuarios(){
        ModeloTablaUsuarios m;

        m=(ModeloTablaUsuarios) tablaUsuarios.getModel();
        m.setFilas(fa.obtenerUsuario(buscarID.getText(),buscarNombre.getText()));
        if (m.getRowCount() > 0) {
            tablaUsuarios.setRowSelectionInterval(0, 0);
            cargarSeleccion();
        }
        
    }
    public void cargarSeleccion(){
        textoIdNuevo.setEditable(true);
        Usuario usr =((ModeloTablaUsuarios)tablaUsuarios.getModel()).getUsuario(tablaUsuarios.getSelectedRow());
        textoIdNuevo.setText(usr.getIdUsuario());
        textoIdNuevo.setEditable(false);
        textoNombreNuevo.setText(usr.getNombre());
        textoClave.setText(usr.getClave());
        textoEmail.setText(usr.getEmail());
        textoDireccion.setText(usr.getDireccion());
        if(usr.getTipoUsuario().equals(TipoUsuario.Administrador))comboTipo.setSelectedIndex(1);
        else comboTipo.setSelectedIndex(0);
    }
}
